# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.50685585 0.65177641 0.76329937]
  [0.78961114 0.09117561 0.1483223 ]
  [0.25257037 0.41451477 0.43075559]]

 [[0.74145106 0.9525255  0.60622379]
  [0.50647974 0.7867101  0.86348174]
  [0.40238562 0.99287077 0.48381075]]

 [[0.20644227 0.23481525 0.03187265]
  [0.01779808 0.5801334  0.8904703 ]
  [0.4267676  0.27658195 0.59147849]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np
x = np.diag([1, 2, 3, 4,0])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 5.  How to find common values between two arrays?

In [6]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[0 1 0 0 0 1]
Second array:
[1 0 1 0 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)


Original array:
[0.08039081 0.47991433 0.29399106 0.06861649 0.49158252 0.35484133
 0.27576498 0.08341283 0.40685574 0.50245547]
Maximum value replaced by -1:
[ 0.08039081  0.47991433  0.29399106  0.06861649  0.49158252  0.35484133
  0.27576498  0.08341283  0.40685574 -1.        ]


# 9. How to print all the values of an array?

In [ ]:
import numpy as np
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)


# 10.Subtract the mean of each row of a matrix

In [11]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.82631129 0.76661108 0.34195366 0.31756789 0.89996625 0.97357774
  0.05403505 0.7383892  0.97427385 0.92425859]
 [0.45319793 0.25301398 0.02058697 0.99030849 0.12906932 0.05061147
  0.16686255 0.93300183 0.71551598 0.10980465]
 [0.8427593  0.53393689 0.9566743  0.7341959  0.11522572 0.95681473
  0.54828811 0.15422251 0.24255561 0.88950439]
 [0.32891799 0.21427533 0.38282053 0.84274188 0.70056578 0.05834537
  0.11227031 0.43355488 0.03956667 0.29347175]
 [0.99487204 0.87593503 0.81031807 0.79129654 0.03976375 0.7435301
  0.52104262 0.21125972 0.20712927 0.96989393]]

Subtract the mean of each row of the said matrix:

[[ 0.14461683  0.08491662 -0.33974081 -0.36412657  0.21827179  0.29188328
  -0.62765941  0.05669474  0.29257939  0.24256413]
 [ 0.07100061 -0.12918333 -0.36161035  0.60811117 -0.253128   -0.33158584
  -0.21533476  0.55080451  0.33331866 -0.27239266]
 [ 0.24534156 -0.06348086  0.35925655  0.13677816 -0.48219203  0.35939699
  -0.04912963 -0.44319524 -0.35

# 12.How to get the diagonal of a dot product?

In [ ]:
a = np.arange(4).reshape(2,2)
a
array([[0, 1],
       [2, 3]])
a.diagonal()
array([0, 3])
a.diagonal(1)
array([1])


# 13.How to find the most frequent value in an array?

In [14]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[4 3 1 2 2 9 9 3 0 3 3 8 9 0 3 6 8 3 0 5 4 5 4 8 7 7 6 7 6 2 8 2 5 9 6 9 1
 3 1 4]
Most frequent value in the above array:
3


# 14.How to get the n largest values of an array

In [15]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [16]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
